[package]
name    = "mimesis-rs"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/HentaiStorm/mimesis-rs/"
homepage   = "https://github.com/HentaiStorm/mimesis-rs/"
license    = "GNU General Public License v3.0"
authors    = ["HS <github.com/HentaiStorm>"]

keywords   = ["faker", "data", "generator", "random"]
publish    = ["mimesis-rs"]
readme     = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.24.3"
strum = "0.11.0"

obfstr = "0.4.1"

[features]
default = ["all_locales", "all_providers"]

all_locales = [
    "cs", "da", "de", "de-at", "de-ch", "el", "en", "en-au",
    "en-ca", "en-gb", "es", "es-mx", "et", "fa", "fi", "fr",
    "hu", "is", "it", "ja", "kk", "ko", "nl", "nl-be", "no",
    "pl", "pt", "pt-br", "ru", "sk", "sv", "tr", "uk", "zh",
]

cs    = []
da    = []
de    = []
de-at = []
de-ch = []
el    = []
en    = []
en-au = []
en-ca = []
en-gb = []
es    = []
es-mx = []
et    = []
fa    = []
fi    = []
fr    = []
hu    = []
is    = []
it    = []
ja    = []
kk    = []
ko    = []
nl    = []
nl-be = []
no    = []
pl    = []
pt    = []
pt-br = []
ru    = []
sk    = []
sv    = []
tr    = []
uk    = []
zh    = []

all_providers = [
    "address", "binaryfile", "choice", "code",
    "cryptographic", "date", "development",
    "file", "finance", "food", "hardware",
    "internet", "numeric", "path", "payment",
    "person", "science", "text", "transport",
]
address       = []
binaryfile    = []
choice        = []
code          = []
cryptographic = []
date          = []
development   = ["internet"]
file          = ["text"]
finance       = []
food          = []
hardware      = []
internet      = ["date", "file", "text"]
numeric       = []
path          = []
payment       = ["person"]
person        = []
science       = []
text          = []
transport     = []

obfdata = []
